# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s1tEkxhwqJ61qFeVpREmseqwJhfr4Ii5
"""

import pandas as pd
import streamlit as st

Caricamento dei dati dai file Excel

def load_data():
job_data = pd.read_excel('Tempi Target 2025.xlsx', sheet_name='TM_010525')
job_pregiati = pd.read_excel('Tempi Target 2025.xlsx', sheet_name='job pregiati')
return job_data, job_pregiati

job_data, job_pregiati = load_data()

Funzione per ottenere il tempo target e il fattore di pregiatezza

def get_job_details(jobtype):
try:
row = job_data[job_data['JOBTYPE'] == jobtype].iloc[0]
tempo_target = row["Peso=TM Ore  '25"]
if jobtype in job_pregiati['Jobtype'].values:
fattore = job_pregiati[job_pregiati['Jobtype'] == jobtype]['Fattore di Pregiatezza'].values[0]
else:
fattore = 0
return tempo_target, fattore
except IndexError:
return 0, 0

st.title("Calcolo Premio TOF")

Input dei dati

giorni_lavorativi = st.number_input('Giorni Lavorativi', min_value=1, max_value=31, value=20)
ore_ferie = st.number_input('Ore Ferie', min_value=0.0, value=0.0)
ore_permessi = st.number_input('Ore Permessi', min_value=0.0, value=0.0)
ore_formazione = st.number_input('Ore Formazione', min_value=0.0, value=0.0)
num_jobtype = st.number_input('Numero Jobtype', min_value=1, max_value=10, value=3)

Jobtype e quantità

jobtypes = []
quantities = []
for i in range(int(num_jobtype)):
jobtype = st.selectbox(f'Seleziona Jobtype {i+1}', job_data['JOBTYPE'].unique())
quantity = st.number_input(f'Quantità {i+1}', min_value=1, value=1)
jobtypes.append(jobtype)
quantities.append(quantity)

Calcolo del premio

if st.button("Calcola Premio"):
punti_totali = 0
for jobtype, qty in zip(jobtypes, quantities):
punti_standard, fattore_pregiatezza = get_job_details(jobtype)
punti_pregiati = punti_standard * fattore_pregiatezza
punti_totali += (punti_standard * qty) + (punti_pregiati * qty)
st.write(f"Jobtype: {jobtype}, Quantità: {qty}, Punti Standard: {punti_standard:.2f}, Punti Pregiati: {punti_pregiati:.2f}")

premio = punti_totali * 1.1
st.success(f"Premio Totale: {premio:.2f} €")