# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s1tEkxhwqJ61qFeVpREmseqwJhfr4Ii5
"""

import pandas as pd
import streamlit as st

# # Caricamento dei dati dai file Excel

def load\_data():
job\_data = pd.read\_excel('Tempi Target 2025.xlsx', sheet\_name='TM\_010525')
job\_pregiati = pd.read\_excel('Tempi Target 2025.xlsx', sheet\_name='job pregiati')
return job\_data, job\_pregiati

job\_data, job\_pregiati = load\_data()

# Funzione per ottenere il tempo target e il fattore di pregiatezza

def get\_job\_details(jobtype):
try:
row = job\_data\[job\_data\['JOBTYPE'] == jobtype].iloc\[0]
tempo\_target = row\["Peso=TM Ore  '25"]
if jobtype in job\_pregiati\['Jobtype'].values:
fattore = job\_pregiati\[job\_pregiati\['Jobtype'] == jobtype]\['Fattore di Pregiatezza'].values\[0]
else:
fattore = 0
return tempo\_target, fattore
except IndexError:
return 0, 0

st.title("Calcolo Premio TOF")

# Input dei dati

giorni\_lavorativi = st.number\_input('Giorni Lavorativi', min\_value=1, max\_value=31, value=20)
ore\_ferie = st.number\_input('Ore Ferie', min\_value=0.0, value=0.0)
ore\_permessi = st.number\_input('Ore Permessi', min\_value=0.0, value=0.0)
ore\_formazione = st.number\_input('Ore Formazione', min\_value=0.0, value=0.0)
num\_jobtype = st.number\_input('Numero Jobtype', min\_value=1, max\_value=10, value=3)

# Jobtype e quantità

jobtypes = \[]
quantities = \[]
for i in range(int(num\_jobtype)):
jobtype = st.selectbox(f'Seleziona Jobtype {i+1}', job\_data\['JOBTYPE'].unique())
quantity = st.number\_input(f'Quantità {i+1}', min\_value=1, value=1)
jobtypes.append(jobtype)
quantities.append(quantity)

# Calcolo del premio

if st.button("Calcola Premio"):
punti\_totali = 0
for jobtype, qty in zip(jobtypes, quantities):
punti\_standard, fattore\_pregiatezza = get\_job\_details(jobtype)
punti\_pregiati = punti\_standard \* fattore\_pregiatezza
punti\_totali += (punti\_standard \* qty) + (punti\_pregiati \* qty)
st.write(f"Jobtype: {jobtype}, Quantità: {qty}, Punti Standard: {punti\_standard:.2f}, Punti Pregiati: {punti\_pregiati:.2f}")

```
premio = punti_totali * 1.1
st.success(f"Premio Totale: {premio:.2f} €")
```